version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - working_directory: /opt/
      - checkout # check out the code in the project directory
      - run: apt-get update && apt-get install git -y && cd celerystalk && ./setup/install.sh